[profile.default]
fork_url =  "https://base-mainnet.rpc.x.superfluid.dev/"
eth_rpc_url =  "https://base-mainnet.rpc.x.superfluid.dev/"

#### fork_block_number = 27174171  # Lock to a specific block for consistent caching
no_storage_caching = false
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "@superfluid-finance/ethereum-contracts/=lib/protocol-monorepo/packages/ethereum-contracts/",
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/"
]

[rpc_endpoints]
base = "https://base-mainnet.rpc.x.superfluid.dev/"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
